import { Book } from '@/types';

// 29개의 실제 책 데이터 - 실제 이미지와 매칭
export const books: Book[] = [
  {
    id: 1,
    title: "심여사는 킬러",
    author: "강지영",
    coverImage: "/images/bookcover/강지영_심여사는 킬러.jpg",
    audioFile: "/audio/심여사는 킬러.mp3",
    description: "평범해 보이는 심여사의 숨겨진 정체와 스릴러",
    genre: "미스터리",
    publishedYear: 2023,
  },
  {
    id: 2,
    title: "화성의 아이",
    author: "김성중",
    coverImage: "/images/bookcover/김성중_화성의 아이.jpg",
    audioFile: "/audio/화성의 아이.mp3",
    description: "화성에서 태어난 아이의 지구 적응기",
    genre: "SF",
    publishedYear: 2023,
  },
  {
    id: 3,
    title: "뿌리주의자",
    author: "김수우",
    coverImage: "/images/bookcover/김수우_뿌리주의자.jpg",
    audioFile: "/audio/뿌리주의자.mp3",
    description: "근본과 정체성에 대한 철학적 탐구",
    genre: "철학",
    publishedYear: 2023,
    showCopyrightPopup: true,
  },
  {
    id: 4,
    title: "무지개 눈",
    author: "김숨",
    coverImage: "/images/bookcover/김숨_무지개 눈.jpg",
    audioFile: "/audio/무지개 눈.mp3",
    description: "세상을 다채롭게 바라보는 특별한 시선",
    genre: "문학",
    publishedYear: 2023,
  },
  {
    id: 5,
    title: "밤새들의 도시",
    author: "김주혜",
    coverImage: "/images/bookcover/김주혜_밤새들의 도시.jpg",
    audioFile: "/audio/밤새들의 도시.mp3",
    description: "밤에 깨어나는 도시의 숨겨진 이야기",
    genre: "도시소설",
    publishedYear: 2023,
  },
  {
    id: 6,
    title: "파견자들",
    author: "김초엽",
    coverImage: "/images/bookcover/김초엽_파견자들.jpg",
    audioFile: "/audio/파견자들.mp3",
    description: "미래에서 온 파견자들의 미션",
    genre: "SF",
    publishedYear: 2023,
  },
  {
    id: 7,
    title: "남겨진 자들의 삶",
    author: "마테오 비앙키",
    coverImage: "/images/bookcover/마테오 비앙키_남겨진 자들의 삶.jpg",
    audioFile: "/audio/남겨진 자들의 삶.mp3",
    description: "재앙 이후 살아남은 자들의 생존기",
    genre: "포스트 아포칼립스",
    publishedYear: 2023,
  },
  {
    id: 8,
    title: "몬테코어",
    author: "요나스 하센 케미리",
    coverImage: "/images/bookcover/몬테코어_요나스 하센 케미리.jpg",
    audioFile: "/audio/몬테코어.mp3",
    description: "이민자의 삶과 정체성에 대한 성찰",
    genre: "자전소설",
    publishedYear: 2023,
    showCopyrightPopup: true,
  },
  {
    id: 9,
    title: "미친여자들의 무도회",
    author: "빅토리아 마스",
    coverImage: "/images/bookcover/빅토리아 마스_미친여자들의 무도회.jpg",
    audioFile: "/audio/미친 여자들의 무도회.mp3",
    description: "여성들의 광기와 자유에 대한 역사적 탐구",
    genre: "역사소설",
    publishedYear: 2023,
  },
  {
    id: 10,
    title: "혼모노",
    author: "성해나",
    coverImage: "/images/bookcover/성해나_혼모노.jpg",
    audioFile: "/audio/혼모노.mp3",
    description: "진짜와 가짜 사이의 모호한 경계",
    genre: "현대문학",
    publishedYear: 2023,
    showCopyrightPopup: true,
  },
  {
    id: 11,
    title: "언젠가 모든 것은 바다로 떨어진다",
    author: "세라 핀스커",
    coverImage: "/images/bookcover/세라 핀스커_언젠가 모든 것은 바다로 떨어진다.jpg",
    audioFile: "/audio/언젠가 모든 것은 바다로 떨어진다.mp3",
    description: "시간과 공간을 넘나드는 환상적 이야기",
    genre: "환상문학",
    publishedYear: 2023,
    showCopyrightPopup: true,
  },
  {
    id: 12,
    title: "네가 봄에 써야지 속으로 생각했던",
    author: "심보선",
    coverImage: "/images/bookcover/심보선_네가 봄에 써야지 속으로 생각했던.jpg",
    audioFile: "/audio/네가 봄에 써야지 속으로 생각했던.mp3",
    description: "봄에 대한 내밀한 성찰과 시적 감성",
    genre: "시집",
    publishedYear: 2023,
  },
  {
    id: 13,
    title: "봄은 또 오고",
    author: "아드리앵 파를랑주",
    coverImage: "/images/bookcover/아드리앵 파를랑주_봄은 또 오고.jpg",
    audioFile: "/audio/봄은 또 오고.mp3",
    description: "계절의 순환과 인생의 반복에 대한 명상",
    genre: "문학",
    publishedYear: 2023,
  },
  {
    id: 14,
    title: "토끼들의 섬",
    author: "엘비라 나바로",
    coverImage: "/images/bookcover/엘비라 나바로_토끼들의 섬.jpg",
    audioFile: "/audio/토끼들의 섬.mp3",
    description: "토끼들만 사는 신비로운 섬의 이야기",
    genre: "판타지",
    publishedYear: 2023,
  },
  {
    id: 15,
    title: "해가 죽던 날",
    author: "옌롄커",
    coverImage: "/images/bookcover/옌롄커_해가 죽던 날.jpg",
    audioFile: "/audio/해가 죽던 날.mp3",
    description: "종말의 순간을 맞이하는 인간들의 모습",
    genre: "문학",
    publishedYear: 2023,
  },
  {
    id: 16,
    title: "그러나 누군가는 더 검은 밤을 원한다",
    author: "우다영",
    coverImage: "/images/bookcover/우다영_그러나 누군가는 더 검은 밤을 원한다.jpg",
    audioFile: "/audio/그러나 누군가는 더 검은 밤을 원한다.mp3",
    description: "어둠 속에서 찾는 희망과 절망의 경계",
    genre: "현대문학",
    publishedYear: 2023,
  },
  {
    id: 17,
    title: "유리 광장에서",
    author: "윤은성",
    coverImage: "/images/bookcover/윤은성_유리 광장에서.jpg",
    audioFile: "/audio/유리 광장에서.mp3",
    description: "투명한 공간에서 마주하는 인간관계",
    genre: "현대문학",
    publishedYear: 2023,
  },
  {
    id: 18,
    title: "알로하, 나의 엄마들",
    author: "이금이",
    coverImage: "/images/bookcover/이금이_알로하, 나의 엄마들.jpg",
    audioFile: "/audio/알로하, 나의 엄마들.mp3",
    description: "다문화 가정의 따뜻한 이야기",
    genre: "가족소설",
    publishedYear: 2023,
    showCopyrightPopup: true,
  },
  {
    id: 19,
    title: "내 얼굴이 도착하지 않았다",
    author: "이설야",
    coverImage: "/images/bookcover/이설야_내 얼굴이 도착하지 않았다.jpg",
    audioFile: "/audio/내 얼굴이 도착하지 않았다.mp3",
    description: "정체성과 존재에 대한 실험적 소설",
    genre: "실험문학",
    publishedYear: 2023,
    showCopyrightPopup: true,
  },
  {
    id: 20,
    title: "춤을 추었어",
    author: "이수지",
    coverImage: "/images/bookcover/이수지_춤을 추었어.jpg",
    audioFile: "/audio/춤을 추었어.mp3",
    description: "몸짓으로 표현하는 감정과 이야기",
    genre: "그림책",
    publishedYear: 2023,
    isPictureBook: true,
  },
  {
    id: 21,
    title: "그리하여 흘려 쓴 것들",
    author: "이제니",
    coverImage: "/images/bookcover/이제니_그리하여 흘려 쓴 것들.jpg",
    audioFile: "/audio/그리하여 흘려 쓴 것들.mp3",
    description: "일상에서 흘려보낸 생각들의 기록",
    genre: "에세이",
    publishedYear: 2023,
  },
  {
    id: 22,
    title: "눈에 덜 띄는",
    author: "이훤",
    coverImage: "/images/bookcover/이훤_눈에 덜 띄는.jpg",
    audioFile: "/audio/눈에 덜 띄는.mp3",
    description: "평범함 속에 숨겨진 특별함",
    genre: "현대문학",
    publishedYear: 2023,
  },
  {
    id: 23,
    title: "오리배가 지나간 호수의 파랑",
    author: "장이지",
    coverImage: "/images/bookcover/장이지_오리배가 지나간 호수의 파랑.jpg",
    audioFile: "/audio/오리배가 지나간 호수의 파랑.mp3",
    description: "잔잔한 호수 위의 서정적 이야기",
    genre: "서정소설",
    publishedYear: 2023,
  },
  {
    id: 24,
    title: "시차와 시대착오",
    author: "전하영",
    coverImage: "/images/bookcover/전하영_시차와 시대착오.jpg",
    audioFile: "/audio/시차와 시대착오.mp3",
    description: "시간의 차이가 만들어내는 혼란과 깨달음",
    genre: "시집",
    publishedYear: 2023,
  },
  {
    id: 25,
    title: "단 한 사람",
    author: "최진영",
    coverImage: "/images/bookcover/최진영_단 한 사람.jpg",
    audioFile: "/audio/단 한 사람.mp3",
    description: "인생에서 가장 소중한 한 사람에 대한 이야기",
    genre: "현대문학",
    publishedYear: 2023,
  },
  {
    id: 26,
    title: "시스터스 브라더스",
    author: "패트릭 드윗",
    coverImage: "/images/bookcover/패트릭 드윗_시스터스 브라더스.jpg",
    audioFile: "/audio/시스터스 브라더스.mp3",
    description: "서부 시대 형제 킬러들의 모험",
    genre: "서부소설",
    publishedYear: 2023,
  },
  {
    id: 27,
    title: "제주도우다",
    author: "현기영",
    coverImage: "/images/bookcover/현기영_제주도우다.jpg",
    audioFile: "/audio/제주도우다.mp3",
    description: "제주도의 역사와 문화를 담은 대하소설",
    genre: "역사소설",
    publishedYear: 2023,
    showCopyrightPopup: true,
  },
  {
    id: 28,
    title: "숨과 입자",
    author: "황여정",
    coverImage: "/images/bookcover/황여정_숨과 입자.jpg",
    audioFile: "/audio/숨과 입자.mp3",
    description: "생명의 본질에 대한 과학적 상상력",
    genre: "SF",
    publishedYear: 2023,
    showCopyrightPopup: true,
  },
  {
    id: 29,
    title: "적절한 세계의 적절할 수밖에 없는 나",
    author: "후즈키 유미",
    coverImage: "/images/bookcover/후즈키 유미_적절한 세계의 적절할 수밖에 없는 나.jpg",
    audioFile: "/audio/적절한 세계의 적절할 수밖에 없는 나.mp3",
    description: "은밀하고 축축한 감정의 늪지대",
    genre: "일본문학",
    publishedYear: 2023,
    showCopyrightPopup: true,
  },
];